# 新增自动搜索词-同类第一步接口数据
auto_search_data_noe:
  ad_type: sp
  rule_model: A
  module: "sp_auto_search_a_normal"
  campaign_configs:
    - asin_down_limit: 1.8
      asin_up_limit: 2.5
      campaign_id: 386582096614556
      campaign_name: "US-17*33in 电暖垫-自动1-B0F3W5JF4W"
      enable_shared_data: 1
      hight_down_limit: 1.8
      hight_up_limit: 2.5
      low_related_up_limit: 0.1
      price: 39.99
      profit_margin_down_limit: 0
      strategy_config: 0
      target_acos: 35
      target_cr: 20
  ad_group_configs:
    - ad_campaign_rule_type: null
      ad_campaign_type: "sp_auto_a_campaign"
      ad_group_id: 549607339142042
      ad_group_name: "自动1-紧密"
      ad_group_type: "sp_auto_search_a_group"
      ad_type: "sp"
      campaign_id: 386582096614556
      campaign_name: "US-17*33in 电暖垫-自动1-B0F3W5JF4W"
      default_bid: 2.03
      id: 8791
      manual_targeting: "ProductAuto"
      portfolio_id: 22396183415978
      portfolio_name: "加热垫"
      sys_ad_group_id: 8791
      allowed_campaign_id: 122356139507810
      asin_allowed_campaign_id: 59678734728722
      allowed_campaign_name: "US-17*33in 电暖垫-手动-B0F3W5JF4W"
      asin_allowed_campaign_name: "US-17*33in 电暖垫-ASIN组-B0F3W5JF4W"

# 新增自动搜索词-同类第二步接口数据
auto_search_data_tow:
      policy_task_id: "{{policy_task_id}}"
      keyword_update_data: [ ]
      keyword_related_info_data: [ ]
      asin_update_data: [ ]
      asin_related_info_data: [ ]

# 新增自动搜索词-同类第三步接口数据
auto_search_data_three:
      module: "sp_auto_search_a_normal"
      root_task_id: "{{root_task_id}}"
      keyword_related_info_data: [ ]
      asin_related_info_data: [ ]